name: API Tests - Postman

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Newman
        run: npm install -g newman

      - name: Instalar Reporter HTML
        run: npm install -g newman-reporter-html

      - name: Rodar testes com relatório
        run: |
          newman run collection.json \
          -e environment.json \
          --reporters cli,html \
          --reporter-html-export report.html

        - name: Upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: report-api-tests
          path: report.html
